version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=myaccesskey
      - MINIO_ROOT_PASSWORD=mysecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped  

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue
    command: ["./app", "queue"]
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - S3_TYPE=minio
      - S3_ACCESS_KEY=myaccesskey
      - S3_SECRET_KEY=mysecretkey
      - S3_ADDRESS=minio:9000
      - S3_BUCKET=audio-files
      - LOCAL_STORAGE_TYPE=sqlite
      - LOCAL_STORAGE_FILE_PATH=/local_db/queue.db
    depends_on:
      - minio
    restart: unless-stopped
    volumes:
      - ./local_db:/local_db

  audio_processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio_processor
    command: ["./app", "audio_processor"]
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DEFAULT_AUDIO_NAME=default.mp3
      - S3_TYPE=minio
      - S3_ACCESS_KEY=myaccesskey
      - S3_SECRET_KEY=mysecretkey
      - S3_ADDRESS=minio:9000
      - S3_BUCKET=audio-files
      - QUEUE_CLIENT_HOST=queue
      - QUEUE_CLIENT_PORT=8080
    depends_on:
      - minio
      - queue
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./internal/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./internal/nginx/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - queue
      - audio_processor

volumes:
  minio_data:
    driver: local